//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalCoops.Cocoa.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalCoops.Cocoa.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approuver.
        /// </summary>
        public static string BtnApprove {
            get {
                return ResourceManager.GetString("BtnApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecter.
        /// </summary>
        public static string BtnConnecter {
            get {
                return ResourceManager.GetString("BtnConnecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportateur Vers Excel.
        /// </summary>
        public static string BtnExport {
            get {
                return ResourceManager.GetString("BtnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrer.
        /// </summary>
        public static string btnFilter {
            get {
                return ResourceManager.GetString("btnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string BtnModify {
            get {
                return ResourceManager.GetString("BtnModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau.
        /// </summary>
        public static string BtnNew {
            get {
                return ResourceManager.GetString("BtnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant.
        /// </summary>
        public static string BtnNext {
            get {
                return ResourceManager.GetString("BtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer.
        /// </summary>
        public static string BtnPrint {
            get {
                return ResourceManager.GetString("BtnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rafraichir.
        /// </summary>
        public static string BtnRefresh {
            get {
                return ResourceManager.GetString("BtnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecter.
        /// </summary>
        public static string BtnSignIn {
            get {
                return ResourceManager.GetString("BtnSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string BtnSubmit {
            get {
                return ResourceManager.GetString("BtnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer.
        /// </summary>
        public static string LblConfirm {
            get {
                return ResourceManager.GetString("LblConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot De Passe.
        /// </summary>
        public static string lblPassWord {
            get {
                return ResourceManager.GetString("lblPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom Utilisateur.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
